// This file is generated by scripts/svg-assets.
export const GENERATED_EMPTY_NAMES = [
  'cart',
  'empty',
  'error',
  'favorite',
  'inbox',
  'network',
  'permission',
  'search',
] as const;

export const GENERATED_EMPTY_NAME_MAP = {
  Cart: 'cart',
  Empty: 'empty',
  Error: 'error',
  Favorite: 'favorite',
  Inbox: 'inbox',
  Network: 'network',
  Permission: 'permission',
  Search: 'search',
} as const;

export type GeneratedEmptyName = (typeof GENERATED_EMPTY_NAMES)[number];

export interface GeneratedEmptyPreset {
  title: string;
  description: string;
}

export interface GeneratedEmptyIllustrationMeta {
  label: string;
  source: string;
}

export const GENERATED_EMPTY_PRESETS: Record<GeneratedEmptyName, GeneratedEmptyPreset> = {
  cart: {
    title: 'Cart Empty',
    description: 'Add items you like',
  },
  empty: {
    title: 'No Data',
    description: 'No content to display',
  },
  error: {
    title: 'Loading Failed',
    description: 'Something went wrong',
  },
  favorite: {
    title: 'No Favorites',
    description: 'Your favorites will be here',
  },
  inbox: {
    title: 'No Messages',
    description: 'New messages will appear here',
  },
  network: {
    title: 'Network Error',
    description: 'Please check your connection',
  },
  permission: {
    title: 'No Permission',
    description: 'Permission required to view',
  },
  search: {
    title: 'No Results',
    description: 'Try different keywords',
  },
} as const;

export const GENERATED_EMPTY_META: Record<GeneratedEmptyName, GeneratedEmptyIllustrationMeta> = {
  cart: {
    label: 'Cart',
    source: 'https://www.manypixels.co/gallery?search=cart',
  },
  empty: {
    label: 'Empty',
    source: 'https://www.manypixels.co/gallery?style=isometric&search=empty%20state',
  },
  error: {
    label: 'Error',
    source: 'https://www.manypixels.co/gallery?search=error',
  },
  favorite: {
    label: 'Favorite',
    source: 'https://www.manypixels.co/gallery?search=favorite',
  },
  inbox: {
    label: 'Inbox',
    source: 'https://www.manypixels.co/gallery?search=message',
  },
  network: {
    label: 'Network',
    source: 'https://www.manypixels.co/gallery?search=network',
  },
  permission: {
    label: 'Permission',
    source: 'https://www.manypixels.co/gallery?search=security',
  },
  search: {
    label: 'Search',
    source: 'https://www.manypixels.co/gallery?search=search',
  },
} as const;

export const GENERATED_EMPTY_SVG_TEMPLATES: Record<GeneratedEmptyName, string> = {
  cart: '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 500 360"><path stroke="#d1d3d4" stroke-linecap="round" stroke-width="4" d="M96 312h308" opacity=".75"/><path fill="#fff" stroke="#231f20" stroke-linecap="round" stroke-linejoin="round" stroke-width="8" d="M132 96h42l28 128h132l34-92H194"/><circle cx="226" cy="266" r="18" fill="{{primary}}" stroke="#231f20" stroke-width="8"/><circle cx="322" cy="266" r="18" fill="{{primary}}" stroke="#231f20" stroke-width="8"/><path stroke="#d1d3d4" stroke-linecap="round" stroke-width="10" d="M232 156h88m-76 32h58"/><circle cx="370" cy="92" r="24" fill="#ffb74d"/></svg>',
  empty:
    '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 500 360"><path stroke="#d1d3d4" stroke-linecap="round" stroke-width="4" d="M96 312h308" opacity=".75"/><ellipse cx="250" cy="304" fill="#d1d3d4" opacity=".35" rx="92" ry="18"/><rect width="200" height="132" x="150" y="120" fill="#fff" stroke="#231f20" stroke-width="8" rx="22"/><path fill="{{primarysoft}}" stroke="#231f20" stroke-linejoin="round" stroke-width="8" d="m182 120 22-38h92l22 38"/><path stroke="#d1d3d4" stroke-linecap="round" stroke-width="10" d="M190 178h120m-106 36h92"/><circle cx="358" cy="110" r="28" fill="{{primary}}" opacity=".9"/><path stroke="#fff" stroke-linecap="round" stroke-width="8" d="M344 110h28"/></svg>',
  error:
    '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 500 360"><path stroke="#d1d3d4" stroke-linecap="round" stroke-width="4" d="M96 312h308" opacity=".75"/><rect width="216" height="158" x="142" y="72" fill="#fff" stroke="#231f20" stroke-width="8" rx="20"/><rect width="176" height="88" x="162" y="94" fill="{{primarysoft}}" rx="12"/><path fill="#d1d3d4" stroke="#231f20" stroke-linejoin="round" stroke-width="8" d="M226 230h48l10 48h-68z"/><path stroke="#231f20" stroke-linecap="round" stroke-width="8" d="M190 282h120"/><path stroke="#ff6b6b" stroke-linecap="round" stroke-width="14" d="m216 120 68 68m0-68-68 68"/><path stroke="#d1d3d4" stroke-linecap="round" stroke-width="10" d="M204 210h92"/><circle cx="340" cy="66" r="20" fill="#ff6b6b" opacity=".9"/></svg>',
  favorite:
    '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 500 360"><path stroke="#d1d3d4" stroke-linecap="round" stroke-width="4" d="M96 312h308" opacity=".75"/><rect width="200" height="170" x="150" y="92" fill="#fff" stroke="#231f20" stroke-width="8" rx="18"/><path stroke="#d1d3d4" stroke-linecap="round" stroke-width="10" d="M190 142h120m-120 36h96m-96 36h78"/><path fill="{{primary}}" stroke="#231f20" stroke-linejoin="round" stroke-width="8" d="m350 134 32 24-32 24z"/><path fill="#8bd17c" stroke="#231f20" stroke-linejoin="round" stroke-width="8" d="M250 186c-36-28-70-52-70-88 0-24 18-40 40-40 14 0 24 6 30 16 6-10 16-16 30-16 22 0 40 16 40 40 0 36-34 60-70 88z"/></svg>',
  inbox:
    '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 500 360"><path stroke="#d1d3d4" stroke-linecap="round" stroke-width="4" d="M96 312h308" opacity=".75"/><rect width="244" height="150" x="128" y="116" fill="#fff" stroke="#231f20" stroke-width="8" rx="20"/><path fill="none" stroke="#231f20" stroke-linejoin="round" stroke-width="8" d="m134 130 116 82 116-82"/><circle cx="344" cy="104" r="30" fill="{{primary}}"/><path stroke="#fff" stroke-linecap="round" stroke-width="8" d="M330 104h28"/><path stroke="#d1d3d4" stroke-linecap="round" stroke-width="10" d="M186 278h128"/></svg>',
  network:
    '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 500 360"><path stroke="#d1d3d4" stroke-linecap="round" stroke-width="4" d="M96 312h308" opacity=".75"/><rect width="216" height="158" x="142" y="72" fill="#fff" stroke="#231f20" stroke-width="8" rx="20"/><rect width="176" height="88" x="162" y="94" fill="{{primarysoft}}" rx="12"/><path fill="#d1d3d4" stroke="#231f20" stroke-linejoin="round" stroke-width="8" d="M226 230h48l10 48h-68z"/><path stroke="#231f20" stroke-linecap="round" stroke-width="8" d="M190 282h120"/><path fill="none" stroke="#231f20" stroke-linecap="round" stroke-width="10" d="M196 164c34-30 74-30 108 0m-86 26c22-18 42-18 64 0"/><circle cx="250" cy="218" r="10" fill="#ff6b6b"/><circle cx="340" cy="66" r="20" fill="#ff6b6b" opacity=".9"/></svg>',
  permission:
    '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 500 360"><path stroke="#d1d3d4" stroke-linecap="round" stroke-width="4" d="M96 312h308" opacity=".75"/><path fill="#fff" stroke="#231f20" stroke-linejoin="round" stroke-width="8" d="m250 72 106 42v66c0 66-42 106-106 130-64-24-106-64-106-130v-66z"/><path fill="{{primarysoft}}" d="m250 102 74 30v48c0 46-28 74-74 94-46-20-74-48-74-94v-48z"/><rect width="84" height="70" x="208" y="172" fill="{{primary}}" stroke="#231f20" stroke-width="8" rx="12"/><path fill="none" stroke="#231f20" stroke-linecap="round" stroke-width="8" d="M224 172v-20a26 26 0 0 1 52 0v20"/><circle cx="250" cy="206" r="8" fill="#231f20"/></svg>',
  search:
    '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 500 360"><path stroke="#d1d3d4" stroke-linecap="round" stroke-width="4" d="M96 312h308" opacity=".75"/><rect width="216" height="158" x="142" y="72" fill="#fff" stroke="#231f20" stroke-width="8" rx="20"/><rect width="176" height="88" x="162" y="94" fill="{{primarysoft}}" rx="12"/><path fill="#d1d3d4" stroke="#231f20" stroke-linejoin="round" stroke-width="8" d="M226 230h48l10 48h-68z"/><path stroke="#231f20" stroke-linecap="round" stroke-width="8" d="M190 282h120"/><circle cx="238" cy="138" r="34" fill="#fff" stroke="#231f20" stroke-width="8"/><path stroke="#231f20" stroke-linecap="round" stroke-width="10" d="m264 164 34 34"/><path stroke="#d1d3d4" stroke-linecap="round" stroke-width="10" d="M196 198h108"/><circle cx="340" cy="66" r="20" fill="{{primary}}" opacity=".9"/></svg>',
} as const;
