const fs = require('fs').promises;
const path = require('path');
const { relativeToModule, resolveModulePath } = require('./path-utils');

async function ensureParentDir(filePath) {
  await fs.mkdir(path.dirname(filePath), { recursive: true });
}

function quote(value) {
  return JSON.stringify(value);
}

function toPascalKey(name) {
  return String(name)
    .split(/[-_]/)
    .filter(Boolean)
    .map(part => `${part.charAt(0).toUpperCase()}${part.slice(1)}`)
    .join('');
}

function stableRecord(entries) {
  return Object.fromEntries(entries.sort(([left], [right]) => left.localeCompare(right)));
}

function generateEmptyIllustrationsTs(assets, targetConfig = {}) {
  const emptyAssets = assets
    .filter(asset => asset.target === 'emptyIllustrations')
    .sort((left, right) => left.name.localeCompare(right.name));
  const names = emptyAssets.map(asset => asset.name);
  const nameMap = stableRecord(names.map(name => [toPascalKey(name), name]));
  const presets = stableRecord(
    names.map(name => [
      name,
      targetConfig.presets?.[name] || { title: toPascalKey(name), description: '' },
    ])
  );
  const meta = stableRecord(
    names.map(name => {
      const asset = emptyAssets.find(item => item.name === name);
      return [
        name,
        targetConfig.meta?.[name] || {
          label: toPascalKey(name),
          source: asset?.sourceMeta?.source || '',
        },
      ];
    })
  );
  const templates = stableRecord(emptyAssets.map(asset => [asset.name, asset.content]));

  return `// This file is generated by scripts/svg-assets.
export const GENERATED_EMPTY_NAMES = ${JSON.stringify(names, null, 2)} as const;

export const GENERATED_EMPTY_NAME_MAP = ${JSON.stringify(nameMap, null, 2)} as const;

export type GeneratedEmptyName = typeof GENERATED_EMPTY_NAMES[number];

export interface GeneratedEmptyPreset {
  title: string;
  description: string;
}

export interface GeneratedEmptyIllustrationMeta {
  label: string;
  source: string;
}

export const GENERATED_EMPTY_PRESETS: Record<GeneratedEmptyName, GeneratedEmptyPreset> = ${JSON.stringify(presets, null, 2)} as const;

export const GENERATED_EMPTY_META: Record<GeneratedEmptyName, GeneratedEmptyIllustrationMeta> = ${JSON.stringify(meta, null, 2)} as const;

export const GENERATED_EMPTY_SVG_TEMPLATES: Record<GeneratedEmptyName, string> = ${JSON.stringify(templates, null, 2)} as const;
`;
}

async function emitEmptyIllustrations(assets, targetConfig, options = {}) {
  const outFile = resolveModulePath(targetConfig.outFile);
  const emptyAssets = assets.filter(asset => asset.target === 'emptyIllustrations');
  const writes = [
    {
      target: 'emptyIllustrations',
      path: relativeToModule(outFile),
      count: emptyAssets.length,
      action: options.check ? 'planned' : 'written',
    },
  ];

  if (!options.check) {
    await ensureParentDir(outFile);
    await fs.writeFile(outFile, generateEmptyIllustrationsTs(emptyAssets, targetConfig), 'utf8');
  }

  return { writes };
}

module.exports = {
  emitEmptyIllustrations,
  generateEmptyIllustrationsTs,
  toPascalKey,
  quote,
};
