export type PreviewGroupId = 'basic' | 'form' | 'display' | 'feedback' | 'navigation' | 'advanced';

export interface PreviewComponentMeta {
  name: string;
  label: string;
  title: string;
  desc: string;
  icon: string;
  color: string;
}

export interface PreviewComponentGroup {
  id: PreviewGroupId;
  name: string;
  icon: string;
  color: string;
  components: readonly PreviewComponentMeta[];
}

export const PREVIEW_COMPONENT_GROUPS: readonly PreviewComponentGroup[] = [
  {
    id: 'basic',
    name: '基础组件',
    icon: 'box-seam',
    color: 'primary',
    components: [
      {
        name: 'root',
        label: 'Root',
        title: 'Root 根节点',
        desc: '根节点',
        icon: 'box-seam',
        color: 'primary',
      },
      {
        name: 'button',
        label: 'Button',
        title: 'Button 按钮',
        desc: '按钮',
        icon: 'app-indicator',
        color: 'primary',
      },
      {
        name: 'icon',
        label: 'Icon',
        title: 'Icon 图标',
        desc: '图标',
        icon: 'house',
        color: 'danger',
      },
      { name: 'tag', label: 'Tag', title: 'Tag 标签', desc: '标签', icon: 'tag', color: 'success' },
      {
        name: 'badge',
        label: 'Badge',
        title: 'Badge 徽标',
        desc: '徽标',
        icon: 'bell',
        color: 'warning',
      },
      {
        name: 'avatar',
        label: 'Avatar',
        title: 'Avatar 头像',
        desc: '头像',
        icon: 'house',
        color: 'info',
      },
      {
        name: 'divider',
        label: 'Divider',
        title: 'Divider 分割线',
        desc: '分割线',
        icon: 'house',
        color: 'textSecondary',
      },
      {
        name: 'notice-bar',
        label: 'NoticeBar',
        title: 'NoticeBar 通知栏',
        desc: '通知栏',
        icon: 'house',
        color: 'warning',
      },
      {
        name: 'image',
        label: 'Image',
        title: 'Image 图片',
        desc: '图片',
        icon: 'image',
        color: 'success',
      },
      {
        name: 'grid',
        label: 'Grid',
        title: 'Grid 栅格',
        desc: '栅格',
        icon: 'grid-3x3-gap',
        color: 'primary',
      },
      {
        name: 'space',
        label: 'Space',
        title: 'Space 间距',
        desc: '间距',
        icon: 'arrows-expand',
        color: 'primary',
      },
      {
        name: 'choice',
        label: 'Choice',
        title: 'Choice 快选',
        desc: '快选',
        icon: 'check-square',
        color: 'primary',
      },
    ],
  },
  {
    id: 'form',
    name: '表单组件',
    icon: 'house',
    color: 'success',
    components: [
      {
        name: 'form',
        label: 'Form',
        title: 'Form 表单',
        desc: '表单',
        icon: 'house',
        color: 'primary',
      },
      {
        name: 'form-group',
        label: 'FormGroup',
        title: 'FormGroup 表单分组',
        desc: '表单分组',
        icon: 'folder2-open',
        color: 'success',
      },
      {
        name: 'input',
        label: 'Input',
        title: 'Input 输入框',
        desc: '输入框',
        icon: 'house',
        color: 'primary',
      },
      {
        name: 'textarea',
        label: 'Textarea',
        title: 'Textarea 多行输入',
        desc: '文本域',
        icon: 'house',
        color: 'primary',
      },
      {
        name: 'radio',
        label: 'Radio',
        title: 'Radio 单选框',
        desc: '单选框',
        icon: 'record-circle',
        color: 'success',
      },
      {
        name: 'checkbox',
        label: 'Checkbox',
        title: 'Checkbox 复选框',
        desc: '复选框',
        icon: 'check-square',
        color: 'success',
      },
      {
        name: 'select-list',
        label: 'SelectList',
        title: 'SelectList 选择列表',
        desc: '选择列表',
        icon: 'list-check',
        color: 'success',
      },
      {
        name: 'switch',
        label: 'Switch',
        title: 'Switch 开关',
        desc: '开关',
        icon: 'toggle-on',
        color: 'success',
      },
      {
        name: 'stepper',
        label: 'Stepper',
        title: 'Stepper 步进器',
        desc: '步进器',
        icon: 'plus-slash-minus',
        color: 'warning',
      },
      {
        name: 'slider',
        label: 'Slider',
        title: 'Slider 滑块',
        desc: '滑块',
        icon: 'sliders',
        color: 'warning',
      },
      {
        name: 'rate',
        label: 'Rate',
        title: 'Rate 评分',
        desc: '评分',
        icon: 'star',
        color: 'warning',
      },
      {
        name: 'upload',
        label: 'Upload',
        title: 'Upload 上传',
        desc: '上传',
        icon: 'cloud-upload',
        color: 'info',
      },
      {
        name: 'picker',
        label: 'Picker',
        title: 'Picker 选择器',
        desc: '选择器',
        icon: 'sliders',
        color: 'success',
      },
      {
        name: 'calendar',
        label: 'Calendar',
        title: 'Calendar 日历',
        desc: '日历',
        icon: 'calendar-date',
        color: 'primary',
      },
      {
        name: 'calendar-picker',
        label: 'CalendarPicker',
        title: 'CalendarPicker 日历选择器',
        desc: '日历选择器',
        icon: 'calendar-date',
        color: 'primary',
      },
      {
        name: 'keyboard',
        label: 'Keyboard',
        title: 'Keyboard 虚拟键盘',
        desc: '虚拟键盘',
        icon: 'keyboard',
        color: 'primary',
      },
      {
        name: 'verify-code',
        label: 'VerifyCode',
        title: 'VerifyCode 验证码',
        desc: '验证码输入框',
        icon: 'shield-lock',
        color: 'warning',
      },
    ],
  },
  {
    id: 'display',
    name: '数据展示',
    icon: 'grid-3x3-gap',
    color: 'warning',
    components: [
      {
        name: 'card',
        label: 'Card',
        title: 'Card 卡片',
        desc: '卡片',
        icon: 'credit-card-2-front',
        color: 'primary',
      },
      {
        name: 'cell',
        label: 'Cell',
        title: 'Cell 单元格',
        desc: '单元格',
        icon: 'list-ul',
        color: 'primary',
      },
      {
        name: 'collapse',
        label: 'Collapse',
        title: 'Collapse 折叠面板',
        desc: '折叠面板',
        icon: 'house',
        color: 'primary',
      },
      {
        name: 'timeline',
        label: 'Timeline',
        title: 'Timeline 时间轴',
        desc: '时间轴',
        icon: 'hourglass-split',
        color: 'warning',
      },
      {
        name: 'progress',
        label: 'Progress',
        title: 'Progress 进度条',
        desc: '进度条',
        icon: 'reception-4',
        color: 'info',
      },
      {
        name: 'pull-refresh',
        label: 'PullRefresh',
        title: 'PullRefresh 下拉刷新',
        desc: '下拉刷新',
        icon: 'arrow-clockwise',
        color: 'primary',
      },
      {
        name: 'loading',
        label: 'Loading',
        title: 'Loading 加载',
        desc: '加载',
        icon: 'arrow-clockwise',
        color: 'info',
      },
      {
        name: 'countdown',
        label: 'Countdown',
        title: 'Countdown 倒计时',
        desc: '倒计时',
        icon: 'stopwatch',
        color: 'danger',
      },
      {
        name: 'skeleton',
        label: 'Skeleton',
        title: 'Skeleton 骨架屏',
        desc: '骨架屏',
        icon: 'list-ul',
        color: 'textSecondary',
      },
      {
        name: 'empty',
        label: 'Empty',
        title: 'Empty 空状态',
        desc: '空状态',
        icon: 'inbox',
        color: 'info',
      },
      {
        name: 'carousel',
        label: 'Carousel',
        title: 'Carousel 轮播图',
        desc: '轮播',
        icon: 'house',
        color: 'danger',
      },
      {
        name: 'segmented',
        label: 'Segmented',
        title: 'Segmented 分段器',
        desc: '分段器',
        icon: 'house',
        color: 'primary',
      },
      {
        name: 'number-roller',
        label: 'NumberRoller',
        title: 'NumberRoller 数字翻牌',
        desc: '数字翻牌',
        icon: 'reception-4',
        color: 'info',
      },
      {
        name: 'meta-row',
        label: 'MetaRow',
        title: 'MetaRow 结构行',
        desc: '结构行',
        icon: 'layout-three-columns',
        color: 'primary',
      },
      {
        name: 'horizontal-scroll',
        label: 'HorizontalScroll',
        title: 'HorizontalScroll 横向滚动',
        desc: '横向滚动',
        icon: 'arrows-expand',
        color: 'success',
      },
      {
        name: 'chart-bar',
        label: 'ChartBar',
        title: 'ChartBar 柱状图',
        desc: '柱状图',
        icon: 'reception-4',
        color: 'primary',
      },
      {
        name: 'chart-line',
        label: 'ChartLine',
        title: 'ChartLine 折线图',
        desc: '折线图',
        icon: 'arrow-up-circle',
        color: 'primary',
      },
      {
        name: 'chart-area',
        label: 'ChartArea',
        title: 'ChartArea 面积趋势图',
        desc: '面积趋势',
        icon: 'arrow-up-circle',
        color: 'primary',
      },
      {
        name: 'chart-pie',
        label: 'ChartPie',
        title: 'ChartPie 饼/环图',
        desc: '饼/环图',
        icon: 'record-circle',
        color: 'primary',
      },
      {
        name: 'chart-lite',
        label: 'ChartLite',
        title: 'ChartLite 轻量图表',
        desc: '轻量图表',
        icon: 'arrow-up-circle',
        color: 'primary',
      },
      {
        name: 'chart-ring',
        label: 'ChartRing',
        title: 'ChartRing 环形图',
        desc: '环形图',
        icon: 'record-circle',
        color: 'primary',
      },
      {
        name: 'chart-sparkline',
        label: 'ChartSparkline',
        title: 'ChartSparkline 迷你趋势线',
        desc: '迷你趋势',
        icon: 'arrow-up-circle',
        color: 'primary',
      },
      {
        name: 'chart-stat-card',
        label: 'ChartStatCard',
        title: 'ChartStatCard 指标卡',
        desc: '指标卡',
        icon: 'reception-4',
        color: 'primary',
      },
      {
        name: 'chart-radar-lite',
        label: 'ChartRadarLite',
        title: 'ChartRadarLite 雷达图',
        desc: '雷达图',
        icon: 'layout-three-columns',
        color: 'primary',
      },
    ],
  },
  {
    id: 'feedback',
    name: '反馈组件',
    icon: 'chat-square-dots',
    color: 'danger',
    components: [
      {
        name: 'modal',
        label: 'Modal',
        title: 'Modal 模态框',
        desc: '模态框',
        icon: 'layout-text-window',
        color: 'primary',
      },
      {
        name: 'popup',
        label: 'Popup',
        title: 'Popup 弹出层',
        desc: '弹出层',
        icon: 'layout-three-columns',
        color: 'primary',
      },
      {
        name: 'toast',
        label: 'Toast',
        title: 'Toast 轻提示',
        desc: '轻提示',
        icon: 'chat-right-text',
        color: 'success',
      },
      {
        name: 'action-sheet',
        label: 'ActionSheet',
        title: 'ActionSheet 动作面板',
        desc: '动作面板',
        icon: 'list-task',
        color: 'success',
      },
      {
        name: 'overlay',
        label: 'Overlay',
        title: 'Overlay 遮罩层',
        desc: '遮罩层',
        icon: 'house',
        color: 'textSecondary',
      },
      {
        name: 'tooltip',
        label: 'Tooltip',
        title: 'Tooltip 文字提示',
        desc: '文字提示',
        icon: 'chat-square-quote',
        color: 'info',
      },
      {
        name: 'dropdown',
        label: 'Dropdown',
        title: 'Dropdown 下拉菜单',
        desc: '下拉菜单',
        icon: 'caret-down-square',
        color: 'danger',
      },
      {
        name: 'transition',
        label: 'Transition',
        title: 'Transition 过渡动画',
        desc: '过渡动画',
        icon: 'arrow-clockwise',
        color: 'primary',
      },
      {
        name: 'curtain',
        label: 'Curtain',
        title: 'Curtain 幕帘',
        desc: '幕帘',
        icon: 'grid-3x2',
        color: 'warning',
      },
    ],
  },
  {
    id: 'navigation',
    name: '导航组件',
    icon: 'signpost-split',
    color: 'info',
    components: [
      {
        name: 'navbar',
        label: 'Navbar',
        title: 'Navbar 导航栏',
        desc: '导航栏',
        icon: 'layout-text-window',
        color: 'primary',
      },
      {
        name: 'page',
        label: 'Page',
        title: 'Page 页面容器',
        desc: '页面容器',
        icon: 'layout-three-columns',
        color: 'primary',
      },
      {
        name: 'tab',
        label: 'Tab',
        title: 'Tab 标签页',
        desc: '标签页',
        icon: 'layout-three-columns',
        color: 'primary',
      },
      {
        name: 'tabbar',
        label: 'Tabbar',
        title: 'Tabbar 标签栏',
        desc: '底部导航',
        icon: 'layout-three-columns',
        color: 'success',
      },
      {
        name: 'tabbar-container',
        label: 'TabbarContainer',
        title: 'Tabbar 容器',
        desc: '容器',
        icon: 'layout-three-columns',
        color: 'success',
      },
      {
        name: 'backtop',
        label: 'Backtop',
        title: 'Backtop 回到顶部',
        desc: '返回顶部',
        icon: 'arrow-up-circle',
        color: 'primary',
      },
      {
        name: 'fab',
        label: 'Fab',
        title: 'Fab 悬浮按钮',
        desc: '悬浮按钮',
        icon: 'plus-circle-fill',
        color: 'primary',
      },
      {
        name: 'anchor',
        label: 'Anchor',
        title: 'Anchor 锚点',
        desc: '锚点导航',
        icon: 'signpost-split',
        color: 'primary',
      },
      {
        name: 'sticky',
        label: 'Sticky',
        title: 'Sticky 粘性布局',
        desc: '粘性布局',
        icon: 'pin-angle',
        color: 'primary',
      },
    ],
  },
  {
    id: 'advanced',
    name: '高级组件',
    icon: 'stars',
    color: 'purple',
    components: [
      {
        name: 'virtual-list',
        label: 'VirtualList',
        title: 'VirtualList 虚拟列表',
        desc: '虚拟列表',
        icon: 'list-columns',
        color: 'primary',
      },
      {
        name: 'watermark',
        label: 'Watermark',
        title: 'Watermark 水印',
        desc: '水印',
        icon: 'shield-check',
        color: 'primary',
      },
      {
        name: 'waterfall',
        label: 'Waterfall',
        title: 'Waterfall 瀑布流',
        desc: '瀑布流',
        icon: 'grid-3x2',
        color: 'primary',
      },
    ],
  },
] as const;

export const INTERNAL_PREVIEW_COMPONENTS: readonly PreviewComponentMeta[] = [
  {
    name: 'preload',
    label: 'Preload',
    title: 'Preload 预加载',
    desc: '预加载系统',
    icon: 'lightning-charge-fill',
    color: 'warning',
  },
] as const;

export type PreviewDemoSlug = string;

export const PREVIEW_PUBLIC_COMPONENTS: PreviewComponentMeta[] = PREVIEW_COMPONENT_GROUPS.flatMap(
  group => [...group.components]
);

export const PREVIEW_COMPONENTS = [
  ...PREVIEW_PUBLIC_COMPONENTS,
  ...INTERNAL_PREVIEW_COMPONENTS,
] satisfies PreviewComponentMeta[];

export const PREVIEW_COMPONENT_META_MAP = PREVIEW_COMPONENTS.reduce(
  (map, component) => {
    map[component.name as PreviewDemoSlug] = component;
    return map;
  },
  {} as Record<string, PreviewComponentMeta>
);
