import type { PreviewDemoSlug } from './preview-catalog';

export const PREVIEW_DEMO_SLUGS = [
  'action-sheet',
  'anchor',
  'avatar',
  'backtop',
  'badge',
  'button',
  'calendar',
  'calendar-picker',
  'card',
  'carousel',
  'cell',
  'chart-area',
  'chart-bar',
  'chart-line',
  'chart-lite',
  'chart-pie',
  'chart-radar-lite',
  'chart-ring',
  'chart-sparkline',
  'chart-stat-card',
  'checkbox',
  'choice',
  'collapse',
  'countdown',
  'curtain',
  'divider',
  'dropdown',
  'empty',
  'fab',
  'form',
  'form-group',
  'grid',
  'horizontal-scroll',
  'icon',
  'image',
  'input',
  'keyboard',
  'loading',
  'meta-row',
  'modal',
  'navbar',
  'notice-bar',
  'number-roller',
  'overlay',
  'page',
  'picker',
  'popup',
  'preload',
  'progress',
  'pull-refresh',
  'radio',
  'rate',
  'root',
  'segmented',
  'select-list',
  'skeleton',
  'slider',
  'space',
  'stepper',
  'sticky',
  'switch',
  'tab',
  'tabbar',
  'tabbar-container',
  'tag',
  'textarea',
  'timeline',
  'toast',
  'tooltip',
  'transition',
  'upload',
  'verify-code',
  'virtual-list',
  'waterfall',
  'watermark',
] as const satisfies readonly PreviewDemoSlug[];

const PREVIEW_DEMO_SLUG_SET = new Set<string>(PREVIEW_DEMO_SLUGS);

export function hasPreviewDemo(slug: string): slug is PreviewDemoSlug {
  return PREVIEW_DEMO_SLUG_SET.has(slug);
}
